### PR TITLE
Update metadata flow chart

### PR DESCRIPTION
**Pull request by juliayun23**

### CODE REVIEW

**Review by diodon — COMMENTED** [review]
Thanks for the update. Would it be possible to add a paragraph at the very beginning, before the Summary section to describe what the metadata system is and how it operates, in natural language?

**Comment by juliayun23** [comment]
> Thanks for the update. Would it be possible to add a paragraph at the very beginning, before the Summary section to describe what the metadata system is and how it operates, in natural language?

No problem! I'm drafting that now

**Comment by juliayun23** [comment]
> Thanks for the update. Would it be possible to add a paragraph at the very beginning, before the Summary section to describe what the metadata system is and how it operates, in natural language?

Done.

**Review by diodon — APPROVED** [review]
LGTM thanks!

**Pull request merged**
